# Generated by Django 5.2.7 on 2026-08-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='부스 번호')),
                ('name', models.CharField(max_length=100, verbose_name='서비스명')),
                ('team', models.CharField(max_length=100, verbose_name='팀명')),
                ('tag', models.CharField(choices=[('멋사', '멋사'), ('SJF', 'SJF'), ('AAC', 'AAC'), ('OPEN', 'OPEN')], db_index=True, max_length=10, verbose_name='분류')),
                ('main_content', models.TextField(blank=True, default='', verbose_name='한 줄 소개')),
                ('content', models.TextField(blank=True, default='', verbose_name='상세 설명')),
                ('retrospect', models.TextField(blank=True, default='', verbose_name='회고')),
                ('service_image', models.CharField(blank=True, max_length=300, null=True)),
                ('service_link', models.CharField(blank=True, max_length=300, null=True)),
                ('github_link', models.CharField(blank=True, max_length=300, null=True)),
                ('figma_link', models.CharField(blank=True, max_length=300, null=True)),
                ('recommend_score', models.IntegerField(default=0, verbose_name='추천 가중치')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '부스',
                'verbose_name_plural': '부스',
                'db_table': 'booth',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BoothFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='booths.booth')),
            ],
            options={
                'db_table': 'booth_function',
                'ordering': ['position'],
                'unique_together': {('booth', 'position')},
            },
        ),
        migrations.CreateModel(
            name='BoothTechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack', to='booths.booth')),
            ],
            options={
                'db_table': 'booth_tech_stack',
                'ordering': ['position'],
                'unique_together': {('booth', 'position')},
            },
        ),
        migrations.CreateModel(
            name='BoothView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='booths.booth')),
            ],
            options={
                'db_table': 'booth_view',
                'indexes': [models.Index(fields=['booth', 'viewed_at'], name='booth_view_booth_i_cec396_idx')],
            },
        ),
    ]
