# Generated by Django 5.2.7 on 2026-09-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothImage',
            fields=[
                ('booth_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='부스 번호')),
                ('service_image', models.BinaryField(blank=True, null=True, verbose_name='대표 이미지')),
                ('logo_image', models.BinaryField(blank=True, null=True, verbose_name='로고 이미지')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '부스 이미지',
                'verbose_name_plural': '부스 이미지',
                'db_table': 'booth_image',
                'ordering': ['booth_id'],
            },
        ),
    ]
