# Generated by Django 5.2.7 on 2026-09-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0002_boothimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='retrospect',
        ),
        migrations.AddField(
            model_name='booth',
            name='collaboration',
            field=models.TextField(blank=True, default='', verbose_name='우리 팀의 협업 이야기'),
        ),
        migrations.AddField(
            model_name='booth',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='서로에게 전하는 한 마디'),
        ),
        migrations.AddField(
            model_name='booth',
            name='refactoring',
            field=models.TextField(blank=True, default='', verbose_name='서비스 리팩토링 내용'),
        ),
    ]
