# Generated by Django 5.2.7 on 2026-09-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0003_booth_retrospect_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service', 'service'), ('github', 'github'), ('figma', 'figma'), ('etc', 'etc')], max_length=10)),
                ('position', models.IntegerField()),
                ('url', models.CharField(max_length=500)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='booths.booth')),
            ],
            options={
                'db_table': 'booth_link',
                'ordering': ['kind', 'position'],
                'unique_together': {('booth', 'kind', 'position')},
            },
        ),
    ]
