# Generated by Django 5.2.7 on 2026-09-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0004_boothlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('image', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booth', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photos', to='booths.booth')),
            ],
            options={
                'db_table': 'booth_photo',
                'ordering': ['position'],
                'unique_together': {('booth', 'position')},
            },
        ),
    ]
